server:
  port: 5000
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

#zuul 配置
zuul:
  routes:
    server-a:
      path: /servera/**
      serviceId: server-a

    server-b:
      path: /serverb/**
      serviceId: server-b
