server:
  port: 8080
spring:
  application:
    name: server-a
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    prefer-ip-address: true
my:
  const:
    clientId: server-a
    realm: server-a-realm
    resourceId: server-a-resource