server:
  port: 8080
spring:
  application:
    name: server-a
  #默认用户名和密码
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
#  mvc:
#    static-path-pattern: /**
  security:
    user:
      name: admin
      password: admin
      roles: admin

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    prefer-ip-address: true

my:
  const:
    clientId: server-a
    realm: my_outha_realm
    resourceId: server-res-a

mybatis-plus:
  mapper-locations: classpath*:huang/yong/chang/mapper/mapping/*.xml